version: '2'
services:
  django:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: fabspace.ithacaweb.org
      GEONODE_LB_PORT: 80
      SITEURL: http://fabspace.ithacaweb.org/
      ALLOWED_HOSTS: "['fabspace.ithacaweb.org']"
      GEOSERVER_PUBLIC_LOCATION: http://fabspace.ithacaweb.org/geoserver/

  celery:
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: fabspace.ithacaweb.org
      GEONODE_LB_PORT: 80
      SITEURL: http://fabspace.ithacaweb.org/
      ALLOWED_HOSTS: "['fabspace.ithacaweb.org']"
      GEOSERVER_PUBLIC_LOCATION: http://fabspace.ithacaweb.org/geoserver/

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: fabspace.ithacaweb.org
      GEONODE_LB_PORT: 80
      NGINX_BASE_URL:
